package com.aryanmaheshwari.taskmanager.data.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.io.Serializable

// Sub-items belonging to a Task (e.g. steps generated by the AI task creator)
@Entity(
    tableName = "checklist_item_table",
    foreignKeys = [
        ForeignKey(
            entity = Task::class,
            parentColumns = ["id"],
            childColumns = ["taskId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("taskId")]
)
data class ChecklistItem(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val taskId: Int,          // FK -> Task.id
    val text: String,
    var isChecked: Boolean = false
) : Serializable
